#!/bin/bash

if [ ! -d logs ] ; then 
    mkdir -p logs
fi

if [[ "$1" == 'development' || "$1" == 'production' || "$1" == 'test' || "$1" == 'stats' ]] ; then
    export NODE_ENV="$1";
else
    export NODE_ENV='development';
fi

nohup supervisor -w ./app -p app.js >> ./logs/bozuko.log &
