#!/bin/bash 
nodeunit tests/system/*.js \
         tests/mongodb/*.js \
         app/models/test/*.js \
         app/util/test/*.js \
         app/core/test/*.js \
         app/core/contest/engine/test/*.js \
         app/games/test/*.js
